objects/Api_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Endpoint_URL__c</fullName>
        <label>Endpoint URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Environment_Name__c</fullName>
        <label>Environment Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>175</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <label>UserName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Api Configuration</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Api Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Api Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestCloudPortalGetUpdatedAccJob.cls
@IsTest
public class TestCloudPortalGetUpdatedAccJob {
@IsTest
    public static void TestBatchGetAccNameAndKey()
    {
        Account acc= new Account(Name='acme',Cloud_Portal_Account_Id__c='123666669898',Cloud_Portal_Account_Key__c='934932849343');
        insert acc;
        Api_Configuration__c apicOnfig= new Api_Configuration__c(Base_Endpoint__c='https://portaleng.silverpeaksystems.net/portal',Endpoint_URL__c='https://portaleng.silverpeaksystems.net/portal/apis/rest',Environment_Name__c='Cloud Portal Testing',UserName__c='abc@silver-peak.com',Password__c='test');
        insert apicOnfig;
        Test.setMock(HttpCalloutMock.class, new CloudPortalApiMock(200, 'OK', 'String body', new Map<String, String> ()));
        Test.startTest();
        CloudPortalGetUpdatedAccountsJob obj= new CloudPortalGetUpdatedAccountsJob();
        Database.executeBatch(obj);
        Test.stopTest();
    }
   
}