objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>CC_List_1__c</fullName>
        <label>CC List 1</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CC_List_2__c</fullName>
        <label>CC List 2</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CC_List_3__c</fullName>
        <label>CC List 3</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CC_List_4__c</fullName>
        <label>CC List 4</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CC_List_5__c</fullName>
        <label>CC List 5</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>POC_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>link to contact record for POC communications</inlineHelpText>
        <label>POC Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RSM_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RSM Sales Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>POC_Requests_RSMM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RSM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RSM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>POC_Requests_RSM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SE_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SE Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>POC_Requests_SEM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SE</label>
        <referenceTo>User</referenceTo>
        <relationshipName>POC_Requests_SE</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved to Ship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped - Extended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Return - Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Returned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approvals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped- Pending Extension Approval</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>POC Request</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>POC Requests</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <label>New</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/RMA__c.object
<CustomObject>
    <description>Basic RMA tracking. This is the RMA header and the details of the items associated with the RMA are in the RMA Details.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RMA&apos;s</relationshipLabel>
        <relationshipName>R00N30000000t29BEAQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LineCount__c</fullName>
        <label>LineCount</label>
        <summaryForeignKey>RMA_Item__c.RMA__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Received_Count__c</fullName>
        <label>Received Count</label>
        <summaryFilterItems>
            <field>RMA_Item__c.Status__c</field>
            <operation>equals</operation>
            <value>Received</value>
        </summaryFilterItems>
        <summaryForeignKey>RMA_Item__c.RMA__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>POC Request</label>
        <referenceTo>Request__c</referenceTo>
        <relationshipLabel>RMA&apos;s</relationshipLabel>
        <relationshipName>RMAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Initiated</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Dispatched</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Logistics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RSM Assist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In FA/Recd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dispatch Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dispatch Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RMA</label>
    <nameField>
        <displayFormat>RMA-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>RMA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMA&apos;s</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/RMA_Item__c.object
<CustomObject>
    <description>RMA detail line items that track specific products to be shipped or returned to/from a customer location.</description>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>RMA Items</relationshipLabel>
        <relationshipName>R00N30000000t2EPEAY</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RMA__c</fullName>
        <label>RMA</label>
        <referenceTo>RMA__c</referenceTo>
        <relationshipLabel>RMA Items</relationshipLabel>
        <relationshipName>RMALines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Dispatched</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Initiated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RSM Assist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RMA Item</label>
    <nameField>
        <displayFormat>RMA Item - {YYYY}{MM}{DD}-{0}</displayFormat>
        <label>RMA Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMA Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/POCRequestTriggerHandler.cls
public class POCRequestTriggerHandler implements ITriggerHandler {

    public POCRequestTriggerHandler()
    {
        
    }
    
    public Boolean IsDisabled()
    {
        return false;
    }
    public void BeforeInsert(List<SObject> newItems) 
    {
        if(newItems!=null && newItems.size()>0)
        {
            for(Request__c newReq:(List<Request__c>)newItems)
            {
               
                
            }
        }
        
    }
    public void BeforeUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) 
    {
       
        if(newItems!=null && newItems.size()>0)
        {
            for (Id reqId : newItems.keyset())
            {
                Request__c newPOC=(Request__c)newItems.get(reqId);
                Request__c oldPOC=(Request__c)oldItems.get(reqId);
                
                
            }
            
        }
    }
    public void BeforeDelete(Map<Id,SObject> oldItems) 
    {
        if(oldItems.size()>0)
        {
            for(Id reqId:oldItems.keySet())
            {
               
            }
        }
    }
    public void AfterInsert(Map<Id, SObject> newItems) 
    {

        if(newItems!=null && newItems.size()>0)
        {
            for (Id oppId : newItems.keyset())
            {
                
            }
       
        }
    }
    public void AfterUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) 
    {     
    	Map<Id,Id> mapPocContact= new Map<Id,Id>();
        if(newItems!=null && newItems.size()>0)
        {
            for (Id reqId : newItems.keyset())
            {
                Request__c newPOC= (Request__c)newItems.get(reqId);
                Request__c oldPOC= (Request__c)oldItems.get(reqId);
                if((oldPoc.Status__c=='Shipped- Pending Extension Approval' || oldPoc.Status__c=='Pending Return' || oldPoc.Status__c=='Pending Return - Invoiced' ) && newPOC.Status__c=='Shipped - Extended')
                {
                    mapPocContact.put(newPOC.Id,newPOC.POC_Contact__c);
                }
            }
        }
        DeleteRMAForApprovedPendReturnPOC(mapPocContact);
    }
    public void AfterDelete(Map<Id, SObject> oldItems) 
    {
        if(oldItems!=null && oldItems.size()>0)
        {
            for (Id reqId : oldItems.keyset())
            {
               
            }
             
            
        }
    }
    public void AfterUndelete(Map<Id, SObject> newItems) 
    {
        if(newItems!=null && newItems.size()>0)
        {
            for (Id reqId : newItems.keyset())
            {
                
            }
        }
    }
    
    private void DeleteRMAForApprovedPendReturnPOC(Map<Id,Id> mapReqs)
    {
        List<RMA__c> rmaIdsToDelete= new List<RMA__c>();
        List<Asset> lstAssetToUpdate= new List<Asset>();
        System.Savepoint sp= Database.setSavepoint();
        try
        {
            if(mapReqs.size()>0)
            {
                for(Id pocId:mapReqs.keySet())
                {
                    List<RMA__c> rmaIds = [Select Id,LineCount__c,Received_Count__c,Account__c from RMA__c where Request__c =:pocId and status__c!='Closed'];
                    System.debug('rmaIds.Id'+rmaIds[0].Id);
                    if(rmaIds!=null && rmaIds.size()>0)
                    {
                        for(RMA__c counter:rmaIds)
                        {
                            if(counter.Received_Count__c==0)
                            {
                                rmaIdsToDelete.add(counter);
                            }
                            List<Asset> lstAsset=[Select Id from Asset where Id in (Select Asset__c from RMA_Item__c where RMA__c =: counter.Id and status__c!='Received')];
                            System.debug('lstAsset'+lstAsset);
                            if(lstAsset!=null && lstAsset.size()>0)
                            {
                                for(Asset item: lstAsset)
                                {
                                    item.Status='Customer Evaluation';
                                    lstAssetToUpdate.add(item);
                                }
                            }
                        } 
                    }
                    SendEmailToPOCContactforRMA(pocId,mapReqs.get(pocId));
                }
                if(lstAssetToUpdate.size()>0)
                {
                    update lstAssetToUpdate;
                }
                if(rmaIdsToDelete.size()>0)
                {
                    delete rmaIdsToDelete;
                }
            }
        }
        catch(Exception ex)
        {
            Database.rollback(sp);
        }
    }
    private  void SendEmailToPOCContactforRMA(Id pocId,Id pocContact)
    {
        List<EmailTemplate> template = [select Id from EmailTemplate where Name='Extension Approval Pending Return' limit 1];
        if(template.size() > 0)
        {
            List<String> ccs = getPOCRecipients(pocId);
            ccs.add('notifications@silver-peak.com');
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            email.setTemplateId(template[0].Id);
            email.setTargetObjectId(pocContact);
            email.setCcAddresses(ccs);
            email.setWhatId(pocId);
            email.setsaveAsActivity(false);
            Id orgWideEmail = SilverPeakUtils.getOrganizationWideEmailId('notifications@silver-peak.com');
            if(orgWideEmail != null)
            {
                email.setOrgWideEmailAddressId(orgWideEmail);
            }
            Messaging.sendEmail(new List<Messaging.Email> {email}, true);  
        }
    }
    private List<String> getPOCRecipients(Id pocId)
    {
        List<Request__c> members = [select Id, SE__r.Email,SE_Manager__r.Email,RSM_Manager__r.Email,RSM__r.Email,CC_List_1__c,CC_List_2__c,CC_List_3__c,CC_List_4__c,CC_List_5__c from Request__c where Id=:pocId];
        List<String> emails = new List<String>();
        if(members!=null && members.size()>0)
        {
            if(members[0].SE__r.Email!=null)
            {
                emails.add(members[0].SE__r.Email);
            }
            if(members[0].SE_Manager__r.Email!=null)
            {
                emails.add(members[0].SE_Manager__r.Email);
            }
            if(members[0].RSM_Manager__r.Email!=null)
            {
                emails.add(members[0].RSM_Manager__r.Email);
            }
            if(members[0].RSM__r.Email!=null)
            {
                emails.add(members[0].RSM__r.Email);
            }
            if(members[0].CC_List_1__c!=null)
            {
                emails.add(members[0].CC_List_1__c);
            }
            if(members[0].CC_List_2__c!=null)
            {
                emails.add(members[0].CC_List_1__c);
            }
            if(members[0].CC_List_3__c!=null)
            {
                emails.add(members[0].CC_List_3__c);
            }
            if(members[0].CC_List_4__c!=null)
            {
                emails.add(members[0].CC_List_4__c);
            }
            if(members[0].CC_List_5__c!=null)
            {
                emails.add(members[0].CC_List_5__c);
            }
        }
        
        return emails;
    }
}