objects/RMA__c.object
<CustomObject>
    <description>Basic RMA tracking. This is the RMA header and the details of the items associated with the RMA are in the RMA Details.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RMA&apos;s</relationshipLabel>
        <relationshipName>R00N30000000t29BEAQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>RMA&apos;s</relationshipLabel>
        <relationshipName>R00N30000000t2CnEAI</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>RMA&apos;s</relationshipLabel>
        <relationshipName>R00N30000000t2CsEAI</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Disposition_Notes__c</fullName>
        <label>Disposition Notes</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Disposition__c</fullName>
        <label>Disposition</label>
        <picklist>
            <picklistValues>
                <fullName>Return to Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scrap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENG FA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LANNER FA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO FA REQUIRED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Initiated</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Dispatched</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Logistics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RSM Assist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In FA/Recd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dispatch Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dispatch Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Return for Repair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advance Replace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eval Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recall</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RMA</label>
    <nameField>
        <displayFormat>RMA-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>RMA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMA&apos;s</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/RMA_Item__c.object
<CustomObject>
    <description>RMA detail line items that track specific products to be shipped or returned to/from a customer location.</description>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>RMA Items</relationshipLabel>
        <relationshipName>R00N30000000t2EPEAY</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RMA__c</fullName>
        <label>RMA</label>
        <referenceTo>RMA__c</referenceTo>
        <relationshipLabel>RMA Items</relationshipLabel>
        <relationshipName>RMALines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Dispatched</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Initiated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RSM Assist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Return - Repair and Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return - Refurbish and Stock</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advance - Ship Unit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RMA Item</label>
    <nameField>
        <displayFormat>RMA Item - {YYYY}{MM}{DD}-{0}</displayFormat>
        <label>RMA Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMA Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RMATriggerHandler.cls
public class RMATriggerHandler implements ITriggerHandler {
    Set<Id> caseIds = new Set<Id>();
    public RMATriggerHandler()
    {
        
    }
    
    public Boolean IsDisabled()
    {
        return false;
    }
    public void BeforeInsert(List<SObject> newItems) 
    {
        
        if(newItems!=null && newItems.size()>0)
        {
            
        }
        
    }
    public void BeforeUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) 
    {
        
        if(newItems!=null && newItems.size()>0)
        {
            
            
        }
    }
    public void BeforeDelete(Map<Id,SObject> oldItems) 
    {
        
    }
    public void AfterInsert(Map<Id, SObject> newItems) 
    {
        
        if(newItems!=null && newItems.size()>0)
        {
            for (Id rmaId : newItems.keyset())
            {
                RMA__c newRMA= (RMA__c) newItems.get(rmaId);
                if(newRMA.Case__c != null)
                {
                    caseIds.add(newRMA.Case__c);
                }
            }
            UpdateRMACountOnCase();
        }
    }
    public void AfterUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) 
    {    
        Set<Id> setRMAs= new Set<Id>();
        Set<Id> setRMADispatchIds= new Set<Id>();
        if(newItems!=null && newItems.size()>0)
        {
            for (Id rmaId : newItems.keyset())
            {
                RMA__c newRMA= (RMA__c) newItems.get(rmaId);
                RMA__c oldRMA= (RMA__c) oldItems.get(rmaId);
                if(newRMA.Type__c=='Advance Replace'&& newRMA.Status__c=='In FA/Recd' && oldRMA.Status__c!=newRMA.Status__c)
                {
                    setRMAs.add(rmaId);
                }
                if(newRMA.Status__c == 'Dispatched' && oldRMA.Status__c != 'Dispatched')
                {
                    setRMADispatchIds.add(rmaId);
                }
                if(newRMA.Case__c != oldRma.Case__c)
                {
                    if(newRMA.Case__c != null)
                    {
                        caseIds.add(newRMA.Case__c);
                    }
                    if(oldRma.Case__c != null)
                    {
                        caseIds.add(oldRma.Case__c);
                    }
                }
                
            }
            UpdateRMACountOnCase();
            DispatchRMAItem(setRMADispatchIds);
            SendNotificationtoHardwareEngineering(setRMAs);
        }
        
    }
    public void AfterDelete(Map<Id, SObject> oldItems) 
    {
        if(oldItems!=null && oldItems.size()>0)
        {
            for (Id rmaId : oldItems.keyset())
            {
                RMA__c oldRMA= (RMA__c) oldItems.get(rmaId);
                if(oldRMA.Case__c != null)
                {
                    caseIds.add(oldRMA.Case__c);
                }
            }
            UpdateRMACountOnCase();
        }
    }
    public void AfterUndelete(Map<Id, SObject> newItems) 
    {
        if(newItems!=null && newItems.size()>0)
        {
            for (Id rmaId : newItems.keyset())
            {
                RMA__c newRMA= (RMA__c) newItems.get(rmaId);
                if(newRMA.Case__c != null)
                {
                    caseIds.add(newRMA.Case__c);
                }
            }
            UpdateRMACountOnCase();
        }
    }
    
    private void UpdateRMACountOnCase()
    {
        if(caseIds!=null && caseIds.size()>0)
        {
            List<Case> updatingCases = new List<Case>();
            for(Id caseId : caseIds)
            {
                Integer count = [select count() from RMA__c where Case__c=:caseId];
                Case updatingCase = new Case(Id = caseId, RMA_Count__c = count);
                updatingCases.add(updatingCase);
            }
            update updatingCases;
        }
        
    }
    
    private void DispatchRMAItem(Set<Id> setRMAIds)
    {
        List<RMA_Item__c> items = new List<RMA_Item__c>();
        if(setRMAIds!=null && setRMAIds.size()>0)
        {
            items = [select Id from RMA_Item__c where RMA__c in:setRMAIds];
            if(items.size() > 0)
            {
                update items;
            }
        }
        
    }
    
    private void SendNotificationtoHardwareEngineering(Set<Id> setRMAIds)
    {
        if(setRMAIds!=null && setRMAIds.size()>0)
        {
            List<RMA_Item__c> rmaItems=[Select Id,Asset__r.Name,Asset__r.Product2.Name,RMA__r.Name,RMA__r.Disposition__c,RMA__r.Disposition_Notes__c,RMA__r.Account__r.Name,RMA__r.Contact__r.Id from RMA_Item__c where RMA__c in:setRMAIds];
            if(rmaItems!=null && rmaItems.size()>0)
            {
                List<Messaging.SingleEmailMessage> allmsg = new List<Messaging.SingleEmailMessage>();
                for(RMA_Item__c item:rmaItems)
                {
                    OrgWideEmailAddress owa = [select id, DisplayName, Address from OrgWideEmailAddress where DisplayName='Silver Peak Notifications' limit 1];
                    String templateString='S/N {0} ({1}) has been returned from {2} against {3}.\n\n\n';
                    String[] arguments = new String[] {item.Asset__r.Name, item.Asset__r.Product2.Name,item.RMA__r.Account__r.Name,item.RMA__r.Name};
                        string bodyText= string.format(templateString,arguments);
                    bodyText= bodyText+ 'Disposition Location: '+ item.RMA__r.Disposition__c +'\n';
                    bodyText= bodyText+ 'Notes: '+ item.RMA__r.Disposition_Notes__c;
                    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                    mail.setSaveAsActivity(false);
                    mail.setOrgWideEmailAddressId(owa.id);
                    List<String> sendTo = new List<String>();
                    sendTo.add('hware@silver-peak.com');
                    mail.setToAddresses(sendTo);
                    mail.setSubject(item.RMA__r.Name +' faulty system received');
                    mail.setPlainTextBody (bodyText);
                    List<String> ccTo = new List<String>();
                    ccTo.add('notifications@silver-peak.com');
                    mail.setCcAddresses(ccTo);
                    allmsg.add(mail);
                    
                }
                if(allmsg.size()>0)
                {
                    if(!Test.isRunningTest())
                    {
                        Messaging.sendEmail(allmsg,false);
                    }
                    
                }
                
                
            }
        }
    }
}